modLoader = "javafml" #mandatory
loaderVersion = "[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
issueTrackerURL="https://github.com/lazyMods/baubles-interface/issues" #optional
[[mods]] #mandatory
modId = "baublesinterface" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Baubles Interface" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/baubles-interface" #optional
logoFile="flogo.png" #optional
credits="ME" #optional
authors = "lazy" #optional
description = '''
Interface for Baubles Mod
'''
[[dependencies.baublesinterface]]
modId="baubles"
mandatory=true
versionRange="[1.8.7,]"
ordering="NONE"
side="CLIENT"